name: Deploy Java to AWS S3

on:
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: samplerolesession
          aws-region: us-east-1

      - name: Build artifacts
        working-directory: Project_1/
        run: | 
          mvn install -DskipTests
          ls -l ${{ github.workspace }}
          ls -l target/

      - name: Upload artifact to AWS S3
        run: aws s3 cp Project_1/target/vprofile-v2.war s3://${{ secrets.AWS_S3 }}/
